[project]
name = "pc-remote"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "UrrovenGrrunta", email = "timbro2312@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32",
    "python-snappy>=0.7",
]

[project.scripts]
pc-remote = "pc_remote:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
